In [ ]:
import numpy as np

In [4]:
arr = np.arange(1,6)
arr

array([1, 2, 3, 4, 5])

In [5]:
np.zeros(9).reshape(3,3)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
arr = np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [11]:
arr.dtype

dtype('int64')

In [12]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [25]:
arr = np.arange(1,13)
reshaped = arr.reshape(3,4)
reshaped
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [26]:
arr.mean()

np.float64(6.5)

In [27]:
arr.max()

np.int64(12)

In [28]:
arr[arr%2!=0]

array([ 1,  3,  5,  7,  9, 11])

In [36]:
brr = np.arange(1,10).reshape(3,3)
brr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
crr = np.arange(1,10).reshape(3,3)
crr 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
brr+crr

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [39]:
brr.dot(crr)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [40]:
brr.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [41]:
arr = np.array([[1,2,3],[4,5,6]])

In [45]:
arr[:,0]+10
arr[:,1]+20
arr[:,2]+30

array([33, 36])

In [50]:
crr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
brr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
np.vstack((brr,crr))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
np.hstack((brr,crr))

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])