In [1]:
import numpy as np

In [2]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
arr[1:5]

array([2, 3, 4, 5])

In [4]:
arr[:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[0:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [8]:
arr[0:,0:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [9]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

In [10]:
arr[0:3,1:3]

array([[ 2,  3],
       [ 7,  8],
       [12, 13]])

In [11]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
bool_index = arr%2==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [13]:
arr = arr[bool_index]
arr

array([ 2,  4,  6,  8, 10])

In [15]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([7,8,9,10,11,12])


In [16]:
arr1 + arr2 

array([ 8, 10, 12, 14, 16, 18])

In [17]:
arr1 * arr2

array([ 7, 16, 27, 40, 55, 72])

In [18]:
arr1**arr2

array([         1,        256,      19683,    1048576,   48828125,
       2176782336])

In [19]:
a1 = np.arange(1,31).reshape(6,5)

In [20]:
a1*2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50],
       [52, 54, 56, 58, 60]])