In [1]:
import numpy as np

In [3]:
data = np.array([18,85,78,19,92,88,17,76,95,18,65,70,20,90,85]).reshape(5,3)
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [4]:
data.shape

(5, 3)

In [7]:
np.mean(data[:,0])

np.float64(18.4)

In [8]:
data[:,1]

array([85, 92, 76, 65, 90])

In [9]:
np.max(data[:,2])

np.int64(95)

In [11]:
bool_index =data[:,1]>90

In [12]:
data[bool_index]

array([[19, 92, 88]])

In [13]:
data[:,1] + 5

array([90, 97, 81, 70, 95])

In [14]:
bool_index = data[:,0]>19

In [15]:
data[bool_index]

array([[20, 90, 85]])

In [17]:
np.mean(data,axis =0)

array([18.4, 81.6, 83.2])

In [19]:
bool_index = data[:,1] & data[:,2] >=80

In [20]:
data[bool_index]

array([[19, 92, 88],
       [20, 90, 85]])

In [21]:
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [24]:
data[(data[:,2])<75] =0
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [ 0,  0,  0],
       [20, 90, 85]])