In [1]:
print("hello")

hello


In [2]:
import numpy as np
a = np.array([1,2,3,4,5])

In [3]:
a

array([1, 2, 3, 4, 5])

In [4]:
l1 = [1,4,3,2.5,]
p = np.array(l1)
p

array([1. , 4. , 3. , 2.5])

In [1]:
q = np.arange(1,11)

NameError: name 'np' is not defined

In [2]:
import numpy as np

In [3]:
l = np.arange(1,11)

In [4]:
l

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr = np.zeros((4,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
arr = np.linspace(1,8,7)
arr

array([1.        , 2.16666667, 3.33333333, 4.5       , 5.66666667,
       6.83333333, 8.        ])

In [9]:
np.random.rand(10)

array([0.19433234, 0.39816945, 0.71344848, 0.99770505, 0.3450791 ,
       0.40060767, 0.31758243, 0.54775237, 0.29852595, 0.31755513])

In [12]:
np.random.randint(6)

1

In [13]:
np.random.randint(10,20,5)

array([18, 15, 16, 12, 18], dtype=int32)

In [15]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
arr.size

9

In [17]:
arr.dtype

dtype('int64')

In [18]:
arr.shape

(3, 3)

In [19]:
brr = np.array([[1,9,7],[3,4,5],[6,2,1]])
brr

array([[1, 9, 7],
       [3, 4, 5],
       [6, 2, 1]])

In [24]:
#brr.min()
#brr.max()
brr.sum()

np.int64(38)

In [ ]:
#axis == 0  // sum of each col
np.sum(brr,axis =0)

array([10, 15, 13])

In [ ]:
# axis == 1 // sum of each row 
np.sum(brr,axis =1) 

array([17, 12,  9])

In [28]:
brr.argmax()

np.int64(1)

In [29]:
brr.argmin()

np.int64(0)

In [33]:
arr = np.arange(1,26)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [34]:
arr = arr.reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])